name: Setup TeX Live for eason.sty
description: "Setup TeX Live in EasonSYC/latex-style"

runs:
  using: "composite"

  steps:

  - name: Checkout latex-style
    uses: actions/checkout@v6
    with:
      repository: EasonSYC/latex-style
      path: latex-style

  - name: Install TeX Live
    uses: zauguin/install-texlive@v4
    with:
      package_file: ${{ github.action_path }}/texlive.packages

  - name: Get texmf Path
    shell: bash
    run: |
      echo "texmf_home=$(kpsewhich -var-value TEXMFHOME)" >> $GITHUB_ENV

  - name: Create TeX Local Directory
    shell: bash
    run: |
      mkdir -p ${{ env.texmf_home }}/tex/latex/local

  - name: Link Style Files
    shell: bash
    run: |
      ln -s ${{ github.workspace }}/latex-style/eason.sty ${{ env.texmf_home }}/tex/latex/local/eason.sty
      ln -s ${{ github.workspace }}/latex-style/macros.tex ${{ env.texmf_home }}/tex/latex/local/macros.tex

  - name: Confirm Style Files can be Found
    shell: bash
    run: |
      kpsewhich eason.sty
      kpsewhich macros.tex

  - name: Install Python
    uses: actions/setup-python@v6
    with:
      python-version: '3.14'
  
  - name: Compute Requirements Hash
    shell: bash
    run: echo "pip_hash=$(sha256sum ${{ github.action_path }}/requirements.txt | cut -d' ' -f1)" >> $GITHUB_ENV

  - name: Cache pip
    uses: actions/cache@v5
    with:
      path: ~/cache/.pip
      key: ${{ runner.os }}-pip-${{ env.pip_hash }}
      restore-keys: |
        ${{ runner.os }}-pip-

  - name: Install Pygments
    shell: bash
    run: pip install -r ${{ github.action_path }}/requirements.txt