name: LaTeX Style Setup Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Style Setup Test

    steps:
      - name: Setup TeX Live
        uses: EasonSYC/latex-style-setup@main
